logging:
    file:
        name: greenuniversity.log
        path: /logs
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8081
    servlet:
        context-path: /
spring:
    servlet:
        multipart:
            location: uploads
            max-file-size: 10MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: fafa5271783@gmail.com
        password: kuyk ffoc bbhu vjwf
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    application:
        name: greenuniversity
        version: ${version}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwerty123@
        url: jdbc:mysql://3.34.99.164:3306/Greenuniversity
        username: greenuniversity
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates